name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-lastest
    steps:
      - name: check out the repository code 
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
